

	/*=====================
	+Compare
	======================*/
	

	/*=====================
	+Colorbox
	======================*/
	#closeButton{text-align:right;position:absolute;right:5px;top:5px;z-index:1000}.layerWrap{text-align:left;zoom:1;min-height:200px}#colorbox{background-color:#FFF}#colorbox,#cboxOverlay,#cboxWrapper{position:absolute;top:0;left:0;z-index:1011;overflow:hidden}#cboxOverlay{position:fixed;width:100%;height:100%}body.tablet #cboxOverlay{height:20000px!important}#cboxMiddleLeft,#cboxBottomLeft{clear:left}#cboxContent{position:relative;overflow:visible}#cboxLoadedContent{overflow:auto !important}#cboxLoadedContent iframe{display:block;width:100%;height:100%;border:0 none}#cboxTitle{margin:0}#cboxLoadingOverlay,#cboxLoadingGraphic{position:absolute;top:0;left:0;width:100%}#cboxPrevious,#cboxNext,#cboxClose,#cboxSlideshow{cursor:pointer}#cboxOverlay{background:#000}#cboxContent{margin-top:0}#cboxLoadedContent{background:transparent;padding:1px}#cboxLoadingOverlay{background:#FFF}#cboxTitle{position:absolute;top:-22px;left:0;color:#000}#cboxCurrent{position:absolute;top:-22px;right:205px;text-indent:-9999px}#cboxPrevious{background-position:0 0;right:44px}#cboxPrevious.hover{background-position:0 -25px}#cboxNext{background-position:-25px 0;right:22px}#cboxNext.hover{background-position:-25px -25px}#cboxClose{background-position:-50px 0;position:absolute;top:10px;right:10px}#cboxClose.hover{background-position:-50px -25px}.cboxSlideshow_on #cboxPrevious,.cboxSlideshow_off #cboxPrevious{right:66px}.cboxSlideshow_on #cboxSlideshow{background-position:-75px -25px;right:44px}.cboxSlideshow_on #cboxSlideshow.hover{background-position:-100px -25px}.cboxSlideshow_off #cboxSlideshow{background-position:-100px 0;right:44px}.cboxSlideshow_off #cboxSlideshow.hover{background-position:-75px -25px}

	/*=====================
	+QAS
	======================*/
	#colorbox #QAS_Dialog{display:inline-block}#QAS_Dialog{display:none;padding:20px 10px 10px;box-sizing:border-box}.QAS_PromptText{font-weight:700}.results span.result{display:block}#QAS_Dialog .QAS_Header{margin-bottom:15px}#QAS_Dialog span.original span{display:block}#QAS_Dialog .QAS_Input input#QAS_RefineText{float:left;width:100px}#QAS_Dialog #QAS_Input button{float:left}#QAS_Dialog .QAS_RightSidePromptText .prompt{font-weight:700}#QAS_Dialog .QAS_MultPick span{display:block}#QAS_Dialog span.prompt{font-weight:700}#QAS_Dialog span.warning{font-size:12px;line-height:14px;color:red}#QAS_Dialog .QAS_Pick{display:none}#QAS_Dialog .QAS_Pick span{display:block}#QAS_Dialog .QAS_OR{font-size:20px;font-weight:700;text-align:left}#QAS_Dialog span.prompt,#QAS_Dialog span.original{display:block}#QAS_Wait{display:none;width:240px;height:180px;padding:20px;font-weight:700;background:url(/assets/images/common/loadinfo.gif) no-repeat center center}#QAS_Dialog .or{background:url(/assets/images/common/or.png) no-repeat right center}#QAS_Dialog button.secondary{margin-left:15px}body.mobile #QAS_Dialog{padding:0}body.mobile .QAS_inner{padding:10px}body.mobile #QAS_Dialog button{margin-bottom:10px;width:100%}body.mobile #QAS_Dialog .or{background-image:none}body.mobile #QAS_Dialog button.secondary{margin:0 0 10px 0}

	/*====================
	+Owl
	======================*/
	.owl-carousel .owl-wrapper:after{content:".";display:block;clear:both;visibility:hidden;line-height:0;height:0}.owl-carousel{display:none;position:relative;width:100%;-ms-touch-action:pan-y}.owl-carousel .owl-wrapper{display:none;position:relative;-webkit-transform:translate3d(0,0,0)}.owl-carousel .owl-wrapper-outer{overflow:hidden;position:relative;width:100%}.owl-carousel .owl-wrapper-outer.autoHeight{-webkit-transition:height 500ms ease-in-out;-moz-transition:height 500ms ease-in-out;-ms-transition:height 500ms ease-in-out;-o-transition:height 500ms ease-in-out;transition:height 500ms ease-in-out}.owl-carousel .owl-item{float:left;text-align:center}.owl-controls .owl-page,.owl-controls .owl-buttons div{cursor:pointer}.owl-controls{-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-webkit-tap-highlight-color:rgba(0,0,0,0)}.grabbing{cursor:url(grabbing.png) 8 8,move}.owl-carousel .owl-wrapper,.owl-carousel .owl-item{-webkit-backface-visibility:hidden;-moz-backface-visibility:hidden;-ms-backface-visibility:hidden;-webkit-transform:translate3d(0,0,0);-moz-transform:translate3d(0,0,0);-ms-transform:translate3d(0,0,0)}.owl-next{position:absolute;right:0;top:20%}.owl-prev{position:absolute;left:0;top:20%}.owl-next.disabled{opacity:.5}.owl-prev.disabled{opacity:.5}

	/*====================
	+jScrollPane
	======================*/
	.jspContainer{overflow:hidden;position:relative}.jspPane{position:absolute}.jspVerticalBar{position:absolute;top:0;right:0;width:16px;height:100%;background:red}.jspHorizontalBar{position:absolute;bottom:0;left:0;width:100%;height:16px;background:red}.jspCap{display:none}.jspHorizontalBar .jspCap{float:left}.jspTrack{background:#eee;position:relative}.jspDrag{background-color:#cfcfcf;position:relative;top:0;left:0;cursor:pointer}.jspHorizontalBar .jspTrack,.jspHorizontalBar .jspDrag{float:left;height:100%}.jspArrow{background:#50506d;text-indent:-20000px;display:block;cursor:pointer;padding:0;margin:0}.jspArrow.jspDisabled{cursor:default;background:#80808d}.jspVerticalBar .jspArrow{height:16px}.jspHorizontalBar .jspArrow{width:16px;float:left;height:100%}.jspVerticalBar .jspArrow:focus{outline:none}.jspCorner{background:#eeeef4;float:left;height:100%}* html .jspCorner{margin:0 -3px 0 0}

	/*====================
	+Responsive Tabs
	======================*/
	ul.resp-tabs-list{margin:0;padding:0}.resp-tabs-list li{font-weight:600;font-size:13px;display:inline-block;padding:13px 15px;margin:0;list-style:none;cursor:pointer;float:left}.resp-tabs-container{padding:0;background-color:#fff;clear:left}h2.resp-accordion{cursor:pointer;padding:5px;display:none}.resp-tab-content{display:none;padding:15px}.resp-tab-active{border:1px solid #D9D9D9;border-bottom:none;margin-bottom:-1px;padding:12px 14px 14px 14px}.resp-tab-active{border-bottom:none;background-color:#fff}.resp-content-active,.resp-accordion-active{display:block}.resp-tab-content{border:1px solid #D9D9D9}h2.resp-accordion{font-size:13px;border:1px solid #D9D9D9;border-top:0 solid #D9D9D9;margin:0;padding:10px 15px}h2.resp-tab-active{border-bottom:0 solid #D9D9D9;margin-bottom:0;padding:10px 15px}h2.resp-tab-title:last-child{border-bottom:12px solid #D9D9D9;background:blue}.resp-vtabs ul.resp-tabs-list{float:left;width:30%}.resp-vtabs .resp-tabs-list li{display:block;padding:15px 15px;margin:0;cursor:pointer;float:none}.resp-vtabs .resp-tabs-container{padding:0;background-color:#fff;border:1px solid #c1c1c1;float:left;width:68%;min-height:250px;clear:none}.resp-vtabs .resp-tab-content{border:none}.resp-vtabs li.resp-tab-active{border:1px solid #c1c1c1;border-right:none;background-color:#fff;position:relative;z-index:1;margin-right:-1px}.resp-arrow{width:0;height:0;float:right;margin-top:3px;border-left:6px solid transparent;border-right:6px solid transparent;border-top:12px solid #c1c1c1}h2.resp-tab-active span.resp-arrow{border:none;border-left:6px solid transparent;border-right:6px solid transparent;border-bottom:12px solid #9B9797}.resp-easy-accordion h2.resp-accordion{display:block}.resp-easy-accordion .resp-tab-content{border:1px solid #D9D9D9}.resp-easy-accordion .resp-tab-content:last-child{border-bottom:1px solid #D9D9D9}.resp-jfit{width:100%;margin:0}.resp-tab-content-active{display:block}h2.resp-accordion:first-child{border-top:1px solid #D9D9D9}body.mobile ul.resp-tabs-list{display:none}body.mobile h2.resp-accordion{display:block}body.mobile .resp-vtabs .resp-tab-content.resp-tab-content-active{border-top:none}body.mobile .resp-vtabs .resp-tab-content{border:1px solid #D9D9D9}body.mobile .resp-vtabs .resp-tabs-container{border:none;float:none;width:100%;min-height:inherit;clear:none}body.mobile .resp-accordion-closed{display:none}body.mobile .resp-vtabs .resp-tab-content:last-child{border-bottom:1px solid #D9D9D9}

	/*====================
	+Password Strength
	======================*/
	.passwordStrength{padding-right:5%;float:right}#billing-actual-password .passwordStrength{padding-right:8%}#resetPasswordForm .passwordStrength{padding-right:8.5%}#panelReceipt .passwordStrength{padding-right:7%}.passwordStrength .strength{display:inline-block;text-transform:uppercase;font-weight:700}.passwordStrength .strength.tooshort{color:#d2d2d2}.passwordStrength .strength.weak{color:#f19796}.passwordStrength .strength.medium{color:#f0ba64}.passwordStrength .strength.strong{color:#a7ce73}.passwordStrengthWeak{background-color:#f19796!important;color:#FFF!important}.passwordStrengthMedium{background-color:#f0ba64!important;color:#FFF!important}.passwordStrengthStrong{background-color:#a7ce73!important;color:#FFF!important}